import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { FaInstagram } from "react-icons/fa";
import { MdEmail } from "react-icons/md";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      fallbackRedirectUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL}
      signInFallbackRedirectUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL}
      signUpFallbackRedirectUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL}
    >
      <html lang="en">
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
          {/* Grid layout: header, main, footer */}
          <div className="w-full flex justify-center min-h-screen" style={{ backgroundColor: "#FAFAFA" }}>
        <div className="w-[78%] flex flex-col min-h-screen" style={{ backgroundColor: "	#FAF5F0" }}       >
            
            {/* Optional Header */}
            {/* 
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <SignedOut>
                <SignInButton fallbackRedirectUrl="/shop" />
                <SignUpButton fallbackRedirectUrl="/shop" />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
            */}

            {/* Page Content */}
            {children}

            {/* Footer */}
            <footer className="mt-auto w-[95%] mx-auto bg-white rounded-t-lg py-4 px-6 flex flex-wrap gap-6 items-center justify-center max-w-full box-border">
              <a
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="mailto:your@email.com"
              >
                <MdEmail size={16} aria-hidden />
                Contact Us
              </a>
              <a
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="https://instagram.com/yourhandle"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaInstagram size={16} aria-hidden />
                Check us out on IG
              </a>
            </footer>

</div>
</div>

          {/* </div> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
